[package]
name = "crunch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
actix = "0.13.0"
crossterm = "0.25.0"
chrono = "0.4.22"
